print(type('True'))
print(type(False))
print(type((1, 2, 3)))
print(type(1.5))
print(type([1, 2, 3]))
print(type(2))
print(type(range(5)))
print(type({1, 2, 3}))
print(type(None))
print(type({'foo': 'bar'}))
